# Generated by Django 3.1 on 2021-08-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20210810_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
